version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket s3-cd-assignment --output-template-file outputTemplate.yaml

artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml