version: 0.2
phases:
  # install:
  #   runtime-versions:
  #       python: 3.7
  build:
    commands:
      - sam package --template-file template.yml --parameters ParameterKey=ImageBucket,ParameterValue=serverlessrepo-s3-image-indexer-elast-imagebucket-daiemzlg6id4 --s3-bucket s3-cd-assignment --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml