AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  indexphotos:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index-photos.lambda_handler
      Runtime: python3.7
      CodeUri: ./Lambdas/
  searchphotos:
    Type: AWS::Serverless::Function
    Properties:
      Handler: search-photos.lambda_handler
      Runtime: python3.7
      CodeUri: ./Lambdas/
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      CodeUri: ./Frontend
